apiVersion: v1
kind: Service
metadata:
  name: mcp-server-service
  namespace: sailpoint
spec:
  type: LoadBalancer
  selector:
    app: mcp-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
