apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: sailpoint
spec:
  type: LoadBalancer
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
